import React, { useContext } from 'react';
import Head from 'next/head';
import {
  AppBar,
  Toolbar,
  Typography,
  Container,
  Link,
  ThemeProvider,
  CssBaseline,
  Switch,
  Badge
} from '@material-ui/core';
import { createTheme } from '@material-ui/core/styles';
import NextLink from 'next/link';
import useStyles from '../utils/styles';
import { Store } from '../utils/Store';
import Cookies from 'js-cookie';

function Layout({ title, description, children }) {
  const { state, dispatch } = useContext(Store);
  const { darkMode, cart } = state;

  const theme = createTheme({
    typography: {
      h1: {
        fontSize: '1.6rem',
        fontWeight: 600,
        margin: '1rem 0',
        letterSpacing: '0.1rem'
      },
      h2: {
        fontSize: '1.4rem',
        fontWeight: 500,
        margin: '1rem 0',
        letterSpacing: '0.1rem'
      }
    },
    palette: {
      type: darkMode ? 'dark' : 'light',
      primary: {
        light: '#f1faee',
        main: '#506c94',
        dark: '#203040',
        contrastText: '#FFFFFF',
        secondaryText: '#BDBDBD'
      },
      secondary: {
        light: '#CDDC39',
        main: '#FFC107',
        dark: '#FFA000',
        contrastText: '#212121',
        secondaryText: '#757575'
      }
    }
  });
  const classes = useStyles();
  const darkModeChangeHandler = () => {
    dispatch({ type: darkMode ? 'DARK_MODE_OFF' : 'DARK_MODE_ON' });
    const newDarkMode = !darkMode;
    Cookies.set('darkMode', newDarkMode ? 'ON' : 'OFF');
  };
  return (
    <div>
      <Head>
        <title>
          {title ? `${title} - Brand e-commerce` : 'Brand e-commerce'}
        </title>
        <meta name="description" content="Generated by create next app"></meta>
        {description && <meta name="description" content={description}></meta>}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <AppBar position="static" className={classes.navbar}>
          <Toolbar>
            <NextLink href="/" passHref>
              <Link>
                <Typography className={classes.brand}>Best Shop</Typography>
              </Link>
            </NextLink>
            <div className={classes.grow}></div>
            <div>
              <Switch
                checked={darkMode}
                onChange={darkModeChangeHandler}
              ></Switch>
              <NextLink href="/cart" passHref>
                <Link>
                  {cart.cartItems?.length > 0 ? (
                    <Badge
                      color="secondary"
                      badgeContent={cart.cartItems.length}
                    >
                      Cart
                    </Badge>
                  ) : (
                    'Cart'
                  )}
                </Link>
              </NextLink>
              <NextLink href="/login" passHref>
                <Link>Login</Link>
              </NextLink>
            </div>
          </Toolbar>
        </AppBar>
        <Container className={classes.main}>{children}</Container>
        <footer className={classes.footer}>
          <Typography>All rights reserved.</Typography>
        </footer>
      </ThemeProvider>
    </div>
  );
}

export default Layout;
